Table of Contents
[ADDED]     A Table of Contents to bashlib.

diff --git a/bash/bashlib/bashlib b/bash/bashlib/bashlib
--- a/bash/bashlib/bashlib
+++ b/bash/bashlib/bashlib
@@ -18,12 +18,131 @@
 # ___________________________________________________________________________ #
 #                                                                             #
 #                                                                             #
-# Copyright 2007-2011, lhunath                                                #
+# Copyright 2007-2013, lhunath                                                #
 #   * http://www.lhunath.com                                                  #
 #   * Maarten Billemont                                                       #
 #                                                                             #
 
 
+
+#  ______________________________________________________________________ 
+# |                                                                      |
+# |                                            .:: TABLE OF CONTENTS ::. |
+# |______________________________________________________________________|
+# 
+# ALL FUNCTIONS:
+#
+#     chr decimal
+# Outputs the character that has the given decimal ASCII value.
+#
+#     ord character
+# Outputs the decimal ASCII value of the given character.
+#
+#     hex character
+# Outputs the hexadecimal ASCII value of the given character.
+#
+#     unhex character
+# Outputs the character that has the given decimal ASCII value.
+#
+#     max numbers...
+# Outputs the highest of the given numbers.
+#
+#     min numbers...
+# Outputs the lowest of the given numbers.
+#
+#     exists application
+# Succeeds if the application is in PATH and is executable.
+#
+#     eol message
+# Return termination punctuation for a message, if necessary.
+#
+#     hr pattern [length]
+# Outputs a horizontal ruler of the given length in characters or the terminal column length otherwise.
+#
+#     cloc
+# Outputs the current cursor location as two space-separated numbers: row column.
+#
+#     readwhile command [args]
+# Outputs the characters typed by the user into the terminal's input buffer while running the given command.
+#
+#     pushqueue element ...
+# Pushes the given arguments as elements onto the queue.
+#
+#     popqueue
+# Pops one element off the queue.
+#
+#     log [format] [arguments...]
+# Log an event at a certain importance level.  The event is expressed as a printf(1) format argument.
+#
+#     emit [options] message... [-- [command args...]]
+# Display a message with contextual coloring.
+#
+#     spinner [-code|message... [-- style color textstyle textcolor]]
+# Displays a spinner on the screen that waits until a certain time.
+#
+#     report [-code] [-e] failure-message [success-message]
+# This is a convenience function for replacement of spinner -code.
+#
+#     ask [-optionchars|+default] message...
+# Ask a question and read the user's reply to it.
+#
+#     trim lines ...
+# Trim the whitespace off of the beginning and end of the given lines.
+#
+#     reverse [-0] [elements ...] [<<< elements]
+# Reverse the order of the given elements.
+#
+#     mutex file
+# Open a mutual exclusion lock on the file, unless another process already owns one.
+#
+#     fsleep time
+# Wait for the given (fractional) amount of seconds.
+#
+#     getArgs [options] optstring [args...]
+# Retrieve all options present in the given arguments.
+#
+#     showHelp name description author [option description]...
+# Generate a prettily formatted usage description of the application.
+#
+#     shquote [-e] [argument...]
+# Shell-quote the arguments to make them safe for injection into bash code.
+#
+#     requote [string]
+# Escape the argument string to make it safe for injection into a regex.
+#
+#     shorten [-p pwd] path [suffix]...
+# Shorten an absolute path for pretty printing.
+#
+#     inArray element array
+# Checks whether a certain element is in the given array.
+#
+#     xpathNodes query [files...]
+# Outputs every xpath node that matches the query on a separate line.
+#
+#     hideDebug [on|off]
+# Toggle Bash's debugging mode off temporarily.
+#
+#     stackTrace
+# Output the current script's function execution stack.
+#
+#
+# Generated by:
+genToc() {
+    local line= comments=() usage= whatis= lineno=0
+    while read -r line; do
+        (( ++lineno ))
+
+        [[ $line = '#'* ]] && comments+=("$line") && continue
+        [[ $line = +([[:alnum:]])'() {' ]] && IFS='()' read func _ <<< "$line" && [[ $func != $FUNCNAME ]] && {
+            usage=${comments[3]##'#'+( )}
+            whatis=${comments[5]##'#'+( )}
+            [[ $usage = $func* && $whatis = *. ]] || err "Malformed docs for %s (line %d)." "$func" "$lineno"
+
+            printf '#     %s\n# %s\n#\n' "$usage" "$whatis"
+        }
+        comments=()
+    done < ~/.bin/bashlib
+}
 
 #  ______________________________________________________________________ 
 # |                                                                      |
@@ -54,7 +173,6 @@ spinner=(    '-' \\  '|' '/' )
 crosser=(    '+' 'x' '+' 'x' )
 runner=(     '> >'           \
              '>> '           \
-             '>>>'           \
              ' >>'           )
 
 # Variables for terminal requests.
@@ -197,8 +315,7 @@ min() {
 #
 #       exists application
 #
-# Returns successfully if the application is in PATH and is executable
-# by the current user.
+# Succeeds if the application is in PATH and is executable.
 #
 exists() {
     [[ -x $(type -P "$1" 2>/dev/null) ]]
@@ -245,7 +362,7 @@ hr() {
 #
 #       cloc
 #
-# Outputs the current cursor location as two space-separated numbers: row column
+# Outputs the current cursor location as two space-separated numbers: row column.
 #
 cloc() {
     local old=$(stty -g)
@@ -680,9 +797,7 @@ emit() {
 #  ______________________________________________________________________
 # |__ Spinner ___________________________________________________________|
 #
-#       spinner message... [-- style color textstyle textcolor]
-#           or
-#       spinner -[code]
+#       spinner [-code|message... [-- style color textstyle textcolor]]
 #
 # Displays a spinner on the screen that waits until a certain time.
 # Best used through its interface provided by 'emit'.
@@ -1041,8 +1156,9 @@ trim() {
 #
 #       reverse [-0] [elements ...] [<<< elements]
 #
-# Reverse the order of the given elements.  Elements are read from command
-# arguments or standard input if no element arguments are given.
+# Reverse the order of the given elements.
+# Elements are read from command arguments or standard input if no element
+# arguments are given.
 # They are reversed and output on standard output.
 #
 # If the -0 option is given, input and output are delimited by NUL bytes.
@@ -1111,8 +1227,7 @@ mutex() {
 #
 #       fsleep time
 #
-# Wait for the given amount of seconds.  The amount of seconds may be
-# fractional.
+# Wait for the given (fractional) amount of seconds.
 #
 # This implementation solves the problem portably, assuming that either
 # bash 4.x or a fractional sleep(1) is available.
@@ -1203,6 +1318,7 @@ getArgs() {
 
 
 
+#  ______________________________________________________________________
 # |__ ShowHelp __________________________________________________________|
 #
 #       showHelp name description author [option description]...
@@ -1262,19 +1378,18 @@ showHelp() {
 #  ______________________________________________________________________
 # |__ Quote _____________________________________________________________|
 #
-#       quote [-e] [argument...]
+#       shquote [-e] [argument...]
 #
-# Output a single string where all arguments are quoted
-# such that the string is safe to be passed as shell
-# command arguments as though given arguments had been
-# passed.
-#
-# When no arguments are passed; no output is generated.
+# Shell-quote the arguments to make them safe for injection into bash code.
+# 
+# The result is bash code that represents a series of words, where each
+# word is a literal string argument.  By default, quoting happens using
+# single-quotes.
 #
 #   -e      Use backslashes rather than single quotes.
 #   -d      Use double-quotes rather than single quotes (does NOT disable expansions!).
 #
-quote() {
+shquote() {
 
     # Initialize the defaults.
     local arg escape=0 sq="'\\''" dq='\"' quotedArgs=() type=single
@@ -1313,8 +1428,10 @@ quote() {
 #
 #       requote [string]
 #
-# Output a single string where the first argument is escaped
-# for safe usage as a literal in a regular expression.
+# Escape the argument string to make it safe for injection into a regex.
+#
+# The result is a regular expression that matches the literal argument
+# string.
 #
 requote() {
 
@@ -1333,8 +1450,9 @@ requote() {
 #
 #       shorten [-p pwd] path [suffix]...
 #
-# Shorten an absolute path for pretty printing by cutting
-# off PWD and replacing HOME by ~.
+# Shorten an absolute path for pretty printing.
+# Paths are shortened by replacing the homedir by ~, making it relative and
+# cutting off given suffixes from the end.
 #
 #   -p      Use the given pathname as the base for relative filenames instead of PWD.
 #   path    The path string to shorten.
@@ -1377,8 +1495,8 @@ shorten() {
     fi
 
     # Replace special paths.
-    path=${path#$pwd/}
     path=${path/#$HOME/'~'}
+    path=${path#$pwd/}
 
     # Cut off suffix.
     for suffix; do
@@ -1460,11 +1578,14 @@ xpathNodes() {
 #  ______________________________________________________________________
 # |__ HideDebug _________________________________________________________|
 #
-#       hideDebug [ on | off ]
+#       hideDebug [on|off]
 #
-# Toggle Bash's debugging mode off temporarily.  To hide Bash's debugging
-# output for a function, you should have a hideDebug on as its first line
-# and hideDebug off as its last.
+# Toggle Bash's debugging mode off temporarily.
+# To hide Bash's debugging output for a function, you should have
+#     hideDebug on
+# as its first line, and
+#     hideDebug off
+# as its last.
 #
 hideDebug() {
 
@@ -1484,8 +1605,7 @@ hideDebug() {
 #
 #       stackTrace
 #
-# Retrieve a mapping of a key from the given map or modify the given map by
-# assigning a new value for the given key if stdin is not the terminal.
+# Output the current script's function execution stack.
 #
 stackTrace() {
 
